version: "3"
services:
  app:
    build: .
    volumes:
      - ./src:/app
    command: "tail -f /dev/null"
    working_dir: /app
    ports:
      - 9024:9024
      - 8000:8000
    env_file: src/.env
